# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

cache:
- bundler
- cocoapods

podfile: Example/Podfile

before_install:
- gem install cocoapods --no-ri --no-rdoc
- gem install xcpretty --no-ri --no-rdoc

script:
- xcodebuild -workspace Example/GAIATabPageView.xcworkspace -scheme GAIATabPageView -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -c ; exit ${PIPESTATUS[0]}

